import 'dart:convert';

List<User> userFromJson(String str) => List<User>.from(json.decode(str).map((x) => User.fromJson(x)));

String userToJson(List<User> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class User {
    int? id;
    String emailAddress;
    String password;
    String nickname;

    User({
        this.id,
        required this.emailAddress,
        required this.password,
        required this.nickname,
    });

    factory User.fromJson(Map<String, dynamic> json) => User(
        id: json["id"],
        emailAddress: json["emailAddress"],
        password: json["password"],
        nickname: json["nickname"],
    );

    Map<String, dynamic> toJson() => {
        "id": id, //remove, as the id will be generated by backend api
        "emailAddress": emailAddress,
        "password": password,
        "nickname": nickname,
    };
}